import { mkdir, rm, cp, readFile, writeFile } from 'node:fs/promises'
import { existsSync } from 'node:fs'

const dist = new URL('../dist/', import.meta.url)
await rm(dist, { recursive: true, force: true })
await mkdir(new URL('assets/', dist), { recursive: true })
if (existsSync(new URL('../public/', import.meta.url))) await cp(new URL('../public/', import.meta.url), dist, { recursive: true })

const css = await readFile(new URL('../src/styles.css', import.meta.url), 'utf8')
await writeFile(new URL('assets/main.css', dist), css)

const js = String.raw`
const root = document.getElementById('root')
root.innerHTML = `<main>
  <section class="hero" id="top" aria-labelledby="hero-title">
    <div class="scene-wrap" id="scene" aria-hidden="true"></div>
    <nav aria-label="Primary navigation"><a class="brand" href="#top">Urban Plus Architect</a><a href="#projects">Work</a><a href="#services">Services</a><a href="#contact">Contact</a></nav>
    <div class="hero-copy"><p class="eyebrow fade">Gwalior / India — Architecture Studio</p><h1 id="hero-title" class="reveal-title"><span>Spaces</span><span>that move</span><span>people.</span></h1><p class="hero-text fade">Architecture, interiors and 3D visualization shaped with proportion, restraint and a close reading of how people live.</p><a class="button fade" href="#projects">Explore our work <svg aria-hidden="true" viewBox="0 0 24 24"><path d="M7 17 17 7M9 7h8v8"/></svg></a></div><div class="scroll fade">Scroll</div>
  </section>
  <section class="intro section"><p class="section-kicker reveal">Studio Philosophy</p><h2 class="reveal">We design for how life feels.</h2><p class="lead reveal">Urban Plus Architect approaches each brief through context, proportion, light, material and human experience. We look for the quiet decisions that make a space feel inevitable: a shaded threshold, a wall that catches morning light, a room scaled for conversation, a material that grows warmer with time.</p></section>
  <section class="projects section" id="projects"><div class="section-head reveal"><p class="section-kicker">Selected Projects</p><h2>Editorial studies in space, light and material.</h2></div><div class="project-grid" id="project-grid"></div></section>
  <section class="services section" id="services"><p class="section-kicker reveal">Services</p><div class="service-list reveal" id="services-list"></div></section>
  <section class="philosophy"><h2 class="reveal">Good architecture does not shout.<br>It stays with you.</h2></section>
  <section class="process section"><p class="section-kicker reveal">Process</p><div class="process-line" aria-hidden="true"></div><article class="step reveal"><span>01</span><h3>Discover</h3><p>Listen, map the context and define the emotional intent of the space.</p></article><article class="step reveal"><span>02</span><h3>Develop</h3><p>Shape plans, volumes and material direction with clear design logic.</p></article><article class="step reveal"><span>03</span><h3>Visualize</h3><p>Use 3D views and atmosphere studies to refine decisions before execution.</p></article><article class="step reveal"><span>04</span><h3>Deliver</h3><p>Coordinate details into a calm, buildable and enduring final experience.</p></article></section>
  <section class="contact section" id="contact"><div class="reveal"><p class="section-kicker">Enquiry</p><h2>Have a space in mind?</h2><p class="placeholder">Contact details below are placeholders and should be replaced with Urban Plus Architect’s verified phone, email and social links.</p><a class="whatsapp" href="https://wa.me/910000000000">WhatsApp placeholder</a></div><form class="reveal"><label>Name<input required placeholder="Name"></label><label>Email<input required type="email" placeholder="Email"></label><label>Phone<input required placeholder="Phone"></label><label>Project type<input required placeholder="Project type"></label><label>Budget range<input placeholder="Budget range"></label><label>Message<textarea placeholder="Tell us about the site, scope and timeline."></textarea></label><button class="button" type="submit">Send enquiry</button></form></section>
  <footer><strong>Urban Plus Architect</strong><span>Gwalior, India</span><span>Architecture / Interiors / Spatial Design</span><span>Instagram · Email · Phone (placeholders)</span></footer>
</main>`
const projects=[['The Courtyard House','Residential Architecture','Gwalior / 2026','sand','A calm inward-looking residence organized around shadow, planted edges, and filtered daylight.'],['Monumental Residence','Luxury Residence','Madhya Pradesh / 2025','charcoal','A grounded family home with carved volumes, deep verandahs, and a restrained material palette.'],['Casa 27','Interior Design','Gwalior / 2025','clay','Warm interiors shaped through tactile surfaces, built-in furniture, and precise ambient light.'],['Light & Stone','3D Visualization','India / 2026','stone','Atmospheric visualizations that make scale, shadow, and material decisions legible before construction.']]
const visual=t=>`<div class="project-visual \${t}" role="img" aria-label="Architectural placeholder visual"><span class="gridline v1"></span><span class="gridline v2"></span><span class="gridline h1"></span><span class="gridline h2"></span><div class="mass mass-a"></div><div class="mass mass-b"></div><div class="mass mass-c"></div><div class="sun-slice"></div><div class="caption-line">replaceable project visual</div></div>`
document.getElementById('project-grid').innerHTML=projects.map(p=>`<button class="project-card reveal">\${visual(p[3])}<span class="project-meta">\${p[1]} · \${p[2]}</span><strong>\${p[0]}</strong><p>\${p[4]}</p></button>`).join('')
const services=[['Architecture','Site-responsive homes and spatial concepts developed from climate, proportion, and everyday rituals.'],['Interior Design','Material-led interiors with custom details, calm palettes, lighting strategy, and lived-in refinement.'],['3D Visualization','Cinematic images and walkthrough-ready compositions for confident design decisions and presentations.'],['Consultation','Early-stage guidance for plots, renovations, space planning, feasibility, and design direction.']]
document.getElementById('services-list').innerHTML=services.map((s,i)=>`<button class="\${i===0?'active':''}" aria-expanded="\${i===0}"><span>0\${i+1}</span><strong>\${s[0]}</strong><p>\${s[1]}</p></button>`).join('')
document.querySelectorAll('.service-list button').forEach(btn=>btn.addEventListener('click',()=>{document.querySelectorAll('.service-list button').forEach(b=>{b.classList.remove('active');b.setAttribute('aria-expanded','false')});btn.classList.add('active');btn.setAttribute('aria-expanded','true')}))
const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches
if(!reduced){const io=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting)e.target.animate([{opacity:0,transform:'translateY(28px)'},{opacity:1,transform:'translateY(0)'}],{duration:700,easing:'cubic-bezier(.2,.8,.2,1)',fill:'both'})}),{threshold:.14});document.querySelectorAll('.reveal,.fade').forEach(el=>io.observe(el))}
import('https://esm.sh/three@0.179.1').then(THREE=>{const mount=document.getElementById('scene');const scene=new THREE.Scene();scene.background=new THREE.Color('#efebe3');const camera=new THREE.PerspectiveCamera(38,mount.clientWidth/mount.clientHeight,.1,100);camera.position.set(0,1.15,matchMedia('(max-width:720px)').matches?6.45:5.25);const renderer=new THREE.WebGLRenderer({antialias:true,powerPreference:'high-performance'});renderer.setPixelRatio(Math.min(devicePixelRatio,1.6));renderer.setSize(mount.clientWidth,mount.clientHeight);mount.appendChild(renderer.domElement);scene.add(new THREE.HemisphereLight('#fff','#d4c6b0',1.4));const light=new THREE.DirectionalLight('#fff6e9',2.7);light.position.set(3,5,4);scene.add(light);const group=new THREE.Group();group.position.y=-.62;scene.add(group);[[0,0,0,4.3,.13,1.9],[-.55,.58,.06,3.45,.13,1.5],[.4,1.13,-.08,2.75,.13,1.22],[-1.52,.83,.18,.13,1.55,1.24],[1.38,.68,-.1,.13,1.44,1.58]].forEach((s,i)=>{const mesh=new THREE.Mesh(new THREE.BoxGeometry(s[3],s[4],s[5]),new THREE.MeshStandardMaterial({color:['#cfc3af','#9b9387','#ded7cb','#7d776c','#d8d0c3'][i],roughness:.68}));mesh.position.set(s[0],s[1],s[2]);group.add(mesh)});let mx=0,my=0;addEventListener('pointermove',e=>{mx=(e.clientX/innerWidth-.5)*2;my=-(e.clientY/innerHeight-.5)*2},{passive:true});function tick(t=0){if(!reduced){group.rotation.y+=(mx*.16+Math.sin(t*.00022)*.055-group.rotation.y)*.045;group.rotation.x+=(-my*.075+Math.sin(t*.00017)*.024-group.rotation.x)*.04}camera.position.y=1.15+Math.min(scrollY/innerHeight,1.4)*.28;camera.lookAt(0,.78,0);renderer.render(scene,camera);requestAnimationFrame(tick)}tick();addEventListener('resize',()=>{camera.aspect=mount.clientWidth/mount.clientHeight;camera.updateProjectionMatrix();renderer.setSize(mount.clientWidth,mount.clientHeight)})})
`
await writeFile(new URL('assets/main.js', dist), js)

let html = await readFile(new URL('../index.html', import.meta.url), 'utf8')
html = html.replace('<script type="module" src="/src/main.jsx"></script>', '<link rel="stylesheet" href="./assets/main.css"><script type="module" src="./assets/main.js"></script>')
await writeFile(new URL('index.html', dist), html)
console.log('Built production assets in dist/')
